<?php
/**
 * Shopware Premium Plugins
 * Copyright (c) shopware AG
 *
 * According to our dual licensing model, this plugin can be used under
 * a proprietary license as set forth in our Terms and Conditions,
 * section 2.1.2.2 (Conditions of Usage).
 *
 * The text of our proprietary license additionally can be found at and
 * in the LICENSE file you have received along with this plugin.
 *
 * This plugin is distributed in the hope that it will be useful,
 * with LIMITED WARRANTY AND LIABILITY as set forth in our
 * Terms and Conditions, sections 9 (Warranty) and 10 (Liability).
 *
 * "Shopware" is a registered trademark of shopware AG.
 * The licensing of the plugin does not imply a trademark license.
 * Therefore any rights, title and interest in our trademarks
 * remain entirely with us.
 */

return [
    0 => [
            'id' => '5',
            'template_id' => '2',
            'name' => 'Option 1',
            'description' => '',
            'ordernumber' => '',
            'required' => '0',
            'type' => 'textfield',
            'position' => '0',
            'default_value' => '',
            'placeholder' => '',
            'is_once_surcharge' => '0',
            'max_text_length' => null,
            'min_value' => null,
            'max_value' => null,
            'max_file_size' => '3145728',
            'min_date' => null,
            'max_date' => null,
            'max_files' => '1',
            'interval' => null,
            'could_contain_values' => '0',
            'allows_multiple_selection' => '0',
            'prices' => [
                    0 => [
                            'id' => '7',
                            'option_id' => '5',
                            'value_id' => null,
                            'surcharge' => '0',
                            'percentage' => '10',
                            'is_percentage_surcharge' => '1',
                            'tax_id' => '1',
                            'customer_group_name' => 'Shopkunden',
                            'customer_group_id' => '1',
                        ],
                ],
            'netPrice' => 1.6760000000000002,
            'surcharge' => 1.9944400000000002,
            'tax_id' => '1',
            'tax' => 0.32,
            'isTaxFreeDelivery' => false,
        ],
    1 => [
            'id' => '6',
            'template_id' => '2',
            'name' => 'Option 2',
            'description' => '',
            'ordernumber' => '',
            'required' => '0',
            'type' => 'checkbox',
            'position' => '1',
            'default_value' => '',
            'placeholder' => '',
            'is_once_surcharge' => '0',
            'max_text_length' => null,
            'min_value' => null,
            'max_value' => null,
            'max_file_size' => '3145728',
            'min_date' => null,
            'max_date' => null,
            'max_files' => '1',
            'interval' => null,
            'could_contain_values' => '1',
            'allows_multiple_selection' => '0',
            'prices' => [
                    0 => [
                            'id' => '11',
                            'option_id' => '6',
                            'value_id' => null,
                            'surcharge' => '0',
                            'percentage' => '0',
                            'is_percentage_surcharge' => '0',
                            'tax_id' => '1',
                            'customer_group_name' => 'Shopkunden',
                            'customer_group_id' => '1',
                        ],
                ],
            'tax_id' => '1',
            'netPrice' => 0.0,
            'surcharge' => 0.0,
            'tax' => 0,
            'isTaxFreeDelivery' => false,
            'values' => [
                    0 => [
                            'id' => '3',
                            'option_id' => '6',
                            'name' => 'Checkbox A',
                            'ordernumber' => '08154711-A',
                            'value' => '',
                            'is_default_value' => '0',
                            'position' => '0',
                            'is_once_surcharge' => '0',
                            'media_id' => null,
                            'seo_title' => null,
                            'prices' => [
                                    0 => [
                                            'id' => '8',
                                            'option_id' => null,
                                            'value_id' => '3',
                                            'surcharge' => '0',
                                            'percentage' => '10',
                                            'is_percentage_surcharge' => '1',
                                            'tax_id' => '1',
                                            'customer_group_name' => 'Shopkunden',
                                            'customer_group_id' => '1',
                                        ],
                                ],
                            'netPrice' => 1.6760000000000002,
                            'surcharge' => 1.9944400000000002,
                            'tax_id' => '1',
                            'tax' => 0.32,
                            'isTaxFreeDelivery' => false,
                            'image' => null,
                        ],
                    1 => [
                            'id' => '4',
                            'option_id' => '6',
                            'name' => 'Checkbox-B',
                            'ordernumber' => '08154711-B',
                            'value' => '',
                            'is_default_value' => '0',
                            'position' => '1',
                            'is_once_surcharge' => '0',
                            'media_id' => null,
                            'seo_title' => null,
                            'prices' => [
                                    0 => [
                                            'id' => '9',
                                            'option_id' => null,
                                            'value_id' => '4',
                                            'surcharge' => '0',
                                            'percentage' => '10',
                                            'is_percentage_surcharge' => '1',
                                            'tax_id' => '1',
                                            'customer_group_name' => 'Shopkunden',
                                            'customer_group_id' => '1',
                                        ],
                                ],
                            'netPrice' => 1.6760000000000002,
                            'surcharge' => 1.9944400000000002,
                            'tax_id' => '1',
                            'tax' => 0.32,
                            'isTaxFreeDelivery' => false,
                            'image' => null,
                        ],
                    2 => [
                            'id' => '5',
                            'option_id' => '6',
                            'name' => 'Checkbox C',
                            'ordernumber' => '08154711-C',
                            'value' => '',
                            'is_default_value' => '0',
                            'position' => '2',
                            'is_once_surcharge' => '0',
                            'media_id' => null,
                            'seo_title' => null,
                            'prices' => [
                                    0 => [
                                            'id' => '10',
                                            'option_id' => null,
                                            'value_id' => '5',
                                            'surcharge' => '4.2016806722689',
                                            'percentage' => '0',
                                            'is_percentage_surcharge' => '0',
                                            'tax_id' => '1',
                                            'customer_group_name' => 'Shopkunden',
                                            'customer_group_id' => '1',
                                        ],
                                ],
                            'netPrice' => 4.2016806722689,
                            'surcharge' => 4.999999999999991,
                            'tax_id' => '1',
                            'tax' => 0.8,
                            'isTaxFreeDelivery' => false,
                            'image' => null,
                        ],
                ],
        ],
];
