version: '3'
services:
  web_server:
    build:
      context: ./web_server/
    container_name: $APACHE_CONTAINER_NAME
    depends_on:
      - database_server
    volumes:
      - ../:/var/www/html
      - ./web_server/php_config:/php_config
      - ./data/logs/:/var/log/docker
      - ./data/dumps/:/home
      - ./data/autostart/:/autostart
    ports:
      - ${APACHE_PORT}:80
    links:
      - database_server
      - mailhog_server:mail.server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      SSH_REMOTE_USER: ${SSH_REMOTE_USER}
      SSH_REMOTE_PASSWORD: ${SSH_REMOTE_PASSWORD}
      MYSQL_REMOTE_DATABASE: ${MYSQL_REMOTE_DATABASE}
      MYSQL_REMOTE_USER: ${MYSQL_REMOTE_USER}
      MYSQL_REMOTE_PASSWORD: ${MYSQL_REMOTE_PASSWORD}
      MYSQL_REMOTE_HOST: ${MYSQL_REMOTE_HOST}

      USER_UID: $UID_U
      USER_GID: $GID_U

      PLATTFORM: ${PLATTFORM}
      DOMAIN: ${DOMAIN}
      WEB_PORT: ${APACHE_PORT}

      PHP_VER: ${PHP_VER}
      PHP_XDEBUG: ${PHP_XDEBUG}


  database_server:
    image: mysql:5.7
    container_name: $MYSQL_CONTAINER_NAME
    volumes:
      - ./data/mysql/:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --skip-ssl
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    user: "$UID_U:$GID_U"


  mailhog_server:
    hostname: mailhog.${DOMAIN}
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025


  phpmyadmin_server:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: database_server
    depends_on:
      - database_server


  proxy_server:
    image: kennersoft/proxy:latest
    container_name: $PROXY_CONTAINER_NAME
    volumes:
      - ./data/cert/:/etc/apache2/ssl/
    ports:
      - ${PROXY_PORT}:80
      - 443:443
    links:
      - web_server
    environment:
      DOMAIN: ${DOMAIN}
      SITE_PROXY_DOMAIN: ${SITE_PROXY_DOMAIN}
      PROXY_PORT: ${PROXY_PORT}
    depends_on:
      - web_server
