<?php
/**
 * Shopware Premium Plugins
 * Copyright (c) shopware AG
 *
 * According to our dual licensing model, this plugin can be used under
 * a proprietary license as set forth in our Terms and Conditions,
 * section 2.1.2.2 (Conditions of Usage).
 *
 * The text of our proprietary license additionally can be found at and
 * in the LICENSE file you have received along with this plugin.
 *
 * This plugin is distributed in the hope that it will be useful,
 * with LIMITED WARRANTY AND LIABILITY as set forth in our
 * Terms and Conditions, sections 9 (Warranty) and 10 (Liability).
 *
 * "Shopware" is a registered trademark of shopware AG.
 * The licensing of the plugin does not imply a trademark license.
 * Therefore any rights, title and interest in our trademarks
 * remain entirely with us.
 */

return [
    'content' => [
        0 => [
            'id' => '763',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Strandtuch "Ibiza" ',
            'articleID' => '178',
            'ordernumber' => 'SW10178',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '19,95',
            'netprice' => '16.764705882353',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => '0',
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => 'Stück',
            'mainDetailId' => '407',
            'articleDetailId' => '407',
            'minpurchase' => '1',
            'taxID' => '1',
            'instock' => '77',
            'suppliernumber' => '',
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => '',
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => '',
            'stockmin' => '0',
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '1',
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => [
                'articleID' => 178,
                'articleDetailsID' => 407,
                'ordernumber' => 'SW10178',
                'highlight' => false,
                'description' => 'paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.',
                'description_long' => '

o decertatio. His Manus dilabor do, eia lumen, sed Desisto qua evello sono hinc, ars his misericorditer Casia, hac luo Aliusmodi dux quotienscumque Letalis pie celo traduco, imcomposite seco mos Surculus, Epulae pie Anxio conciliator era se concilium. Terra quam dicto erro prolecto, quo per incommoditas paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.
',
                'esd' => false,
                'articleName' => 'Strandtuch "Ibiza"',
                'taxID' => 1,
                'tax' => 19.0,
                'instock' => 77,
                'isAvailable' => true,
                'weight' => 0.0,
                'shippingtime' => null,
                'pricegroupActive' => false,
                'pricegroupID' => null,
                'length' => 0.0,
                'height' => 0.0,
                'width' => 0.0,
                'laststock' => false,
                'additionaltext' => '',
                'datum' => '2012-08-21',
                'sales' => 7,
                'filtergroupID' => null,
                'priceStartingFrom' => null,
                'pseudopricePercent' => null,
                'sVariantArticle' => null,
                'sConfigurator' => false,
                'metaTitle' => null,
                'shippingfree' => false,
                'suppliernumber' => '',
                'notification' => false,
                'ean' => '',
                'keywords' => '',
                'sReleasedate' => '',
                'template' => '',
                'attributes' => [],
                'attr1' => '',
                'attr2' => '',
                'attr3' => '',
                'attr4' => '',
                'attr5' => '',
                'attr6' => '',
                'attr7' => '',
                'attr8' => '',
                'attr9' => '',
                'attr10' => '',
                'attr11' => '',
                'attr12' => '',
                'attr13' => '',
                'attr14' => '',
                'attr15' => '',
                'attr16' => '',
                'attr17' => null,
                'attr18' => '',
                'attr19' => '',
                'attr20' => '',
                'supplierName' => 'Beachdreams Clothes',
                'supplierImg' => 'http://localhost/customp/media/image/a1/f7/82/beachdreams.png',
                'supplierID' => 12,
                'supplierDescription' => '',
                'supplier_attributes' => [],
                'newArticle' => false,
                'sUpcoming' => false,
                'topseller' => false,
                'valFrom' => 1,
                'valTo' => null,
                'from' => 1,
                'to' => null,
                'price' => '19,95',
                'pseudoprice' => '0',
                'referenceprice' => '0',
                'has_pseudoprice' => false,
                'price_numeric' => 19.949999999999999,
                'pseudoprice_numeric' => 0.0,
                'price_attributes' => [],
                'pricegroup' => 'EK',
                'minpurchase' => 1,
                'maxpurchase' => '100',
                'purchasesteps' => 1,
                'purchaseunit' => null,
                'referenceunit' => null,
                'packunit' => 'Stück',
                'unitID' => null,
                'sUnit' => [
                    'unit' => null,
                    'description' => null,
                ],
                'unit_attributes' => [],
                'image' => [
                    'id' => 445,
                    'position' => null,
                    'source' => 'http://localhost/customp/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                    'description' => '',
                    'extension' => 'jpg',
                    'main' => true,
                    'parentId' => null,
                    'width' => 1698,
                    'height' => 1131,
                    'thumbnails' => [
                        0 => [
                            'source' => 'http://localhost/customp/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                            'retinaSource' => 'http://localhost/customp/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                            'sourceSet' => 'http://localhost/customp/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://localhost/customp/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                            'maxWidth' => '200',
                            'maxHeight' => '200',
                            'attributes' => [],
                        ],
                        1 => [
                            'source' => 'http://localhost/customp/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                            'retinaSource' => 'http://localhost/customp/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                            'sourceSet' => 'http://localhost/customp/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://localhost/customp/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                            'maxWidth' => '600',
                            'maxHeight' => '600',
                            'attributes' => [],
                        ],
                        2 => [
                            'source' => 'http://localhost/customp/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                            'retinaSource' => 'http://localhost/customp/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                            'sourceSet' => 'http://localhost/customp/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://localhost/customp/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                            'maxWidth' => '1280',
                            'maxHeight' => '1280',
                            'attributes' => [],
                        ],
                    ],
                    'attributes' => [],
                    'attribute' => [],
                ],
                'prices' => [
                    0 => [
                        'valFrom' => 1,
                        'valTo' => null,
                        'from' => 1,
                        'to' => null,
                        'price' => '19,95',
                        'pseudoprice' => '0',
                        'referenceprice' => '0',
                        'pseudopricePercent' => null,
                        'has_pseudoprice' => false,
                        'price_numeric' => 19.949999999999999,
                        'pseudoprice_numeric' => 0.0,
                        'price_attributes' => [],
                        'pricegroup' => 'EK',
                        'minpurchase' => 1,
                        'maxpurchase' => '100',
                        'purchasesteps' => 1,
                        'purchaseunit' => null,
                        'referenceunit' => null,
                        'packunit' => 'Stück',
                        'unitID' => null,
                        'sUnit' => [
                            'unit' => null,
                            'description' => null,
                        ],
                        'unit_attributes' => [],
                    ],
                ],
                'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10178',
                'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
            ],
            'amount' => '19,95',
            'amountnet' => '16,76',
            'priceNumeric' => '19.95',
            'image' => [
                'id' => 445,
                'position' => null,
                'source' => 'http://localhost/customp/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                'description' => '',
                'extension' => 'jpg',
                'main' => true,
                'parentId' => null,
                'width' => 1698,
                'height' => 1131,
                'thumbnails' => [
                    0 => [
                        'source' => 'http://localhost/customp/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                        'retinaSource' => 'http://localhost/customp/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                        'sourceSet' => 'http://localhost/customp/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://localhost/customp/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                        'maxWidth' => '200',
                        'maxHeight' => '200',
                        'attributes' => [],
                    ],
                    1 => [
                        'source' => 'http://localhost/customp/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                        'retinaSource' => 'http://localhost/customp/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                        'sourceSet' => 'http://localhost/customp/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://localhost/customp/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                        'maxWidth' => '600',
                        'maxHeight' => '600',
                        'attributes' => [],
                    ],
                    2 => [
                        'source' => 'http://localhost/customp/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                        'retinaSource' => 'http://localhost/customp/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                        'sourceSet' => 'http://localhost/customp/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://localhost/customp/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                        'maxWidth' => '1280',
                        'maxHeight' => '1280',
                        'attributes' => [],
                    ],
                ],
                'attributes' => [],
                'attribute' => [],
                'src' => [
                    'original' => 'http://localhost/customp/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                    0 => 'http://localhost/customp/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                ],
                'srchd' => [
                    'original' => 'http://localhost/customp/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                    0 => 'http://localhost/customp/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 1131,
                        'height' => 1698,
                    ],
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=763',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10178',
            'tax' => '3,19',
        ],
        1 => [
            'id' => '764',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Textfeld',
            'articleID' => '19',
            'ordernumber' => 'SW_TEXTFIELD',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/4c/9e/e6/Tee-Oriental-Jasmine.jpg',
                    0 => 'http://localhost/customp/media/image/fe/ca/74/Tee-Oriental-Jasmine_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/c7/3a/88/Tee-Oriental-Jasmine_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/30/b4/9a/Tee-Oriental-Jasmine_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 4,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 59,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/74/41/d8/Tee-Oriental-Jasmine_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/34/05/a4/Tee-Oriental-Jasmine_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/01/76/8f/Tee-Oriental-Jasmine_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=19',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=764',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_TEXTFIELD',
            'tax' => '0',
        ],
        2 => [
            'id' => '765',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Textbereich',
            'articleID' => '20',
            'ordernumber' => 'SW_TEXTAREA',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/67/9a/28/Tee-Jasmine-Phoenix-Pearls.jpg',
                    0 => 'http://localhost/customp/media/image/2e/9c/be/Tee-Jasmine-Phoenix-Pearls_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/26/1b/86/Tee-Jasmine-Phoenix-Pearls_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/30/a7/d3/Tee-Jasmine-Phoenix-Pearls_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 4,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 47,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/02/b3/d4/Tee-Jasmine-Phoenix-Pearls_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/6e/e6/f8/Tee-Jasmine-Phoenix-Pearls_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/87/5b/27/Tee-Jasmine-Phoenix-Pearls_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=20',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=765',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_TEXTAREA',
            'tax' => '0',
        ],
        3 => [
            'id' => '766',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Nummernfeld',
            'articleID' => '21',
            'ordernumber' => 'SW_NUMBER',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/7b/d5/a5/Tee-Jasmine-Lotus.jpg',
                    0 => 'http://localhost/customp/media/image/96/b8/d1/Tee-Jasmine-Lotus_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/7d/e4/a3/Tee-Jasmine-Lotus_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/e8/7d/09/Tee-Jasmine-Lotus_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 4,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 67,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/eb/be/84/Tee-Jasmine-Lotus_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/ae/33/f9/Tee-Jasmine-Lotus_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/ac/83/ae/Tee-Jasmine-Lotus_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=21',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=766',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_NUMBER',
            'tax' => '0',
        ],
        4 => [
            'id' => '767',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Drop-Down Feld',
            'articleID' => '22',
            'ordernumber' => 'SW_DROPDOWN',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/40/d0/2a/Tee-Tasse-Glas.jpg',
                    0 => 'http://localhost/customp/media/image/96/86/f5/Tee-Tasse-Glas_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/6d/64/9b/Tee-Tasse-Glas_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/45/fd/85/Tee-Tasse-Glas_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 69,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/27/5c/29/Tee-Tasse-Glas_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/5c/64/cb/Tee-Tasse-Glas_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/9d/5c/5d/Tee-Tasse-Glas_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=22',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=767',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_DROPDOWN',
            'tax' => '0',
        ],
        5 => [
            'id' => '768',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Dropdown 3',
            'articleID' => '30',
            'ordernumber' => 'Dropdown3',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/dc/69/17/Prozellen-Tee-Set-Geschenkbox-Aufgereiht.jpg',
                    0 => 'http://localhost/customp/media/image/b3/09/fe/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/4c/5a/d7/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/4e/21/b6/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 92,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/6f/8e/88/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/66/34/d0/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/a3/8a/05/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=30',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=768',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Dropdown3',
            'tax' => '0',
        ],
        6 => [
            'id' => '769',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Mehrfachauswahl',
            'articleID' => '23',
            'ordernumber' => 'SW_MULTIPLE',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/a8/05/dc/Glasbecher-Seite.jpg',
                    0 => 'http://localhost/customp/media/image/e5/6b/c2/Glasbecher-Seite_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/80/74/09/Glasbecher-Seite_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/a8/f7/5c/Glasbecher-Seite_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 3,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 73,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/b6/ae/c4/Glasbecher-Seite_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/b9/e9/17/Glasbecher-Seite_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/f3/bd/56/Glasbecher-Seite_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=23',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=769',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_MULTIPLE',
            'tax' => '0',
        ],
        7 => [
            'id' => '770',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Mehrfachauswahl 2',
            'articleID' => '34',
            'ordernumber' => 'Mehrfachauswahl2',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:36',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/b1/f5/3e/PU-ERH-Tee-Geschenkset-Cover502de34719689.jpg',
                    0 => 'http://localhost/customp/media/image/03/a4/a2/PU-ERH-Tee-Geschenkset-Cover502de34719689_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/22/03/3f/PU-ERH-Tee-Geschenkset-Cover502de34719689_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/18/bd/8b/PU-ERH-Tee-Geschenkset-Cover502de34719689_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 2,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 111,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/f8/ff/34/PU-ERH-Tee-Geschenkset-Cover502de34719689_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/29/93/1d/PU-ERH-Tee-Geschenkset-Cover502de34719689_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/8e/76/2f/PU-ERH-Tee-Geschenkset-Cover502de34719689_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=34',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=770',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Mehrfachauswahl2',
            'tax' => '0',
        ],
        8 => [
            'id' => '771',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Mehrfachauswahl 3',
            'articleID' => '35',
            'ordernumber' => 'Mehrfachauswahl3',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/e9/e7/14/Schwarzer-Tee-Geschenkset-Pychee-Black-Cover.jpg',
                    0 => 'http://localhost/customp/media/image/6b/0e/e7/Schwarzer-Tee-Geschenkset-Pychee-Black-Cover_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/db/73/cc/Schwarzer-Tee-Geschenkset-Pychee-Black-Cover_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/10/7f/eb/Schwarzer-Tee-Geschenkset-Pychee-Black-Cover_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 4,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 123,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/ee/26/91/Schwarzer-Tee-Geschenkset-Pychee-Black-Cover_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/70/c6/0a/Schwarzer-Tee-Geschenkset-Pychee-Black-Cover_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/a0/00/d8/Schwarzer-Tee-Geschenkset-Pychee-Black-Cover_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=35',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=771',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Mehrfachauswahl3',
            'tax' => '0',
        ],
        9 => [
            'id' => '772',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Checkbox',
            'articleID' => '24',
            'ordernumber' => 'SW_CHECK',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/97/64/84/Teekaenchen-Glas-Seite.jpg',
                    0 => 'http://localhost/customp/media/image/8d/d7/56/Teekaenchen-Glas-Seite_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/ae/82/f6/Teekaenchen-Glas-Seite_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/b4/a2/2f/Teekaenchen-Glas-Seite_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 74,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/aa/41/20/Teekaenchen-Glas-Seite_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/f9/2d/ec/Teekaenchen-Glas-Seite_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/a8/05/ec/Teekaenchen-Glas-Seite_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=24',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=772',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_CHECK',
            'tax' => '0',
        ],
        10 => [
            'id' => '773',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Checkbox 2',
            'articleID' => '38',
            'ordernumber' => 'Checkbox2',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/73/3d/e1/Kraftstoff-Sorten.jpg',
                    0 => 'http://localhost/customp/media/image/dd/00/de/Kraftstoff-Sorten_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/12/96/a7/Kraftstoff-Sorten_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/bf/22/a8/Kraftstoff-Sorten_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 135,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/84/e8/94/Kraftstoff-Sorten_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/5a/4c/4d/Kraftstoff-Sorten_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/5b/19/d4/Kraftstoff-Sorten_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=38',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=773',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Checkbox2',
            'tax' => '0',
        ],
        11 => [
            'id' => '774',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Checkbox 3',
            'articleID' => '39',
            'ordernumber' => 'Checkbox3',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/87/80/69/Mehrzwecknudeln-Front-plus-Back.jpg',
                    0 => 'http://localhost/customp/media/image/8a/3e/77/Mehrzwecknudeln-Front-plus-Back_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/f3/24/cc/Mehrzwecknudeln-Front-plus-Back_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/2e/cb/c6/Mehrzwecknudeln-Front-plus-Back_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 6,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 147,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/6a/d1/42/Mehrzwecknudeln-Front-plus-Back_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/d8/58/e8/Mehrzwecknudeln-Front-plus-Back_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/07/13/64/Mehrzwecknudeln-Front-plus-Back_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=39',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=774',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Checkbox3',
            'tax' => '0',
        ],
        12 => [
            'id' => '775',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Einfachauswahl',
            'articleID' => '25',
            'ordernumber' => 'SW_SIMPLE',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/b0/cf/e2/Teekanne-Glas-Zubehoer.jpg',
                    0 => 'http://localhost/customp/media/image/a0/97/50/Teekanne-Glas-Zubehoer_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/a2/d0/92/Teekanne-Glas-Zubehoer_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/5c/a8/97/Teekanne-Glas-Zubehoer_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 3,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 79,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/6c/28/b4/Teekanne-Glas-Zubehoer_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/85/16/14/Teekanne-Glas-Zubehoer_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/2a/00/7c/Teekanne-Glas-Zubehoer_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=25',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=775',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_SIMPLE',
            'tax' => '0',
        ],
        13 => [
            'id' => '776',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Einfachauswahl 1',
            'articleID' => '41',
            'ordernumber' => 'Einfachauswahl1',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/c3/31/4a/Traubenbatterie-Sorten-plus-Packshot502df67dd2497.jpg',
                    0 => 'http://localhost/customp/media/image/9b/a5/8c/Traubenbatterie-Sorten-plus-Packshot502df67dd2497_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/e7/b9/41/Traubenbatterie-Sorten-plus-Packshot502df67dd2497_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/02/44/9f/Traubenbatterie-Sorten-plus-Packshot502df67dd2497_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 6,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 159,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/cf/96/d4/Traubenbatterie-Sorten-plus-Packshot502df67dd2497_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/8f/13/39/Traubenbatterie-Sorten-plus-Packshot502df67dd2497_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/6b/7b/e3/Traubenbatterie-Sorten-plus-Packshot502df67dd2497_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=41',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=776',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Einfachauswahl1',
            'tax' => '0',
        ],
        14 => [
            'id' => '777',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Farbauswahl',
            'articleID' => '26',
            'ordernumber' => 'SW_COLOR_SEL',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/82/95/c4/Glas-Teezubereiter-Seite.jpg',
                    0 => 'http://localhost/customp/media/image/d4/36/4e/Glas-Teezubereiter-Seite_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/fa/ae/e8/Glas-Teezubereiter-Seite_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/80/71/97/Glas-Teezubereiter-Seite_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 3,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 82,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/c6/93/1a/Glas-Teezubereiter-Seite_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/04/bc/9c/Glas-Teezubereiter-Seite_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/5d/15/8f/Glas-Teezubereiter-Seite_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=26',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=777',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_COLOR_SEL',
            'tax' => '0',
        ],
        15 => [
            'id' => '778',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Farbauswahl 3',
            'articleID' => '46',
            'ordernumber' => 'Farbauswahl3',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=46',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=778',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Farbauswahl3',
            'tax' => '0',
        ],
        16 => [
            'id' => '779',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Bildauswahl',
            'articleID' => '27',
            'ordernumber' => 'SW_IMG_SEL',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/3e/f1/c9/Facil-Teezubereiter-Einzelteile-2.jpg',
                    0 => 'http://localhost/customp/media/image/c6/ed/31/Facil-Teezubereiter-Einzelteile-2_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/8b/29/64/Facil-Teezubereiter-Einzelteile-2_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/74/46/7f/Facil-Teezubereiter-Einzelteile-2_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 83,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/ee/85/2e/Facil-Teezubereiter-Einzelteile-2_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/c6/ba/bb/Facil-Teezubereiter-Einzelteile-2_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/94/7a/f9/Facil-Teezubereiter-Einzelteile-2_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=27',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=779',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_IMG_SEL',
            'tax' => '0',
        ],
        17 => [
            'id' => '780',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Bildauswahl 2',
            'articleID' => '48',
            'ordernumber' => 'Bildauswahl2',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '3',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=48',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=780',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=Bildauswahl2',
            'tax' => '0',
        ],
        18 => [
            'id' => '781',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Datei-Upload',
            'articleID' => '28',
            'ordernumber' => 'SW_FILE_UPLOAD',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/1e/7a/1b/Deluxe-Eisteezubereiter-Seite-2.jpg',
                    0 => 'http://localhost/customp/media/image/a1/89/83/Deluxe-Eisteezubereiter-Seite-2_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/b9/a4/8c/Deluxe-Eisteezubereiter-Seite-2_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/45/69/bc/Deluxe-Eisteezubereiter-Seite-2_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 87,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/1b/3e/0c/Deluxe-Eisteezubereiter-Seite-2_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/g0/56/5f/Deluxe-Eisteezubereiter-Seite-2_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/ab/63/d8/Deluxe-Eisteezubereiter-Seite-2_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=28',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=781',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_FILE_UPLOAD',
            'tax' => '0',
        ],
        19 => [
            'id' => '782',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Bild-Upload',
            'articleID' => '29',
            'ordernumber' => 'SW_IMG_UPL',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/67/9f/79/Porzellan-Teeservice.jpg',
                    0 => 'http://localhost/customp/media/image/7e/cc/3f/Porzellan-Teeservice_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/81/54/aa/Porzellan-Teeservice_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/91/c7/b3/Porzellan-Teeservice_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 89,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/1f/ba/d5/Porzellan-Teeservice_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/ce/g0/10/Porzellan-Teeservice_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/d3/51/34/Porzellan-Teeservice_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=29',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=782',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_IMG_UPL',
            'tax' => '0',
        ],
        20 => [
            'id' => '783',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Datumsfeld',
            'articleID' => '30',
            'ordernumber' => 'SW_DATE',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/dc/69/17/Prozellen-Tee-Set-Geschenkbox-Aufgereiht.jpg',
                    0 => 'http://localhost/customp/media/image/b3/09/fe/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/4c/5a/d7/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/4e/21/b6/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 1,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 92,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/6f/8e/88/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/66/34/d0/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/a3/8a/05/Prozellen-Tee-Set-Geschenkbox-Aufgereiht_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=30',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=783',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_DATE',
            'tax' => '0',
        ],
        21 => [
            'id' => '784',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Zeitfeld',
            'articleID' => '31',
            'ordernumber' => 'SW_TIME',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/c2/6e/a5/Gruener-Tee-Geschenkset-Pi-Lo-Chun-Cover.jpg',
                    0 => 'http://localhost/customp/media/image/54/22/fa/Gruener-Tee-Geschenkset-Pi-Lo-Chun-Cover_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/a6/9f/42/Gruener-Tee-Geschenkset-Pi-Lo-Chun-Cover_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/f5/4f/4f/Gruener-Tee-Geschenkset-Pi-Lo-Chun-Cover_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 4,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 98,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/c9/02/9d/Gruener-Tee-Geschenkset-Pi-Lo-Chun-Cover_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/af/9f/d4/Gruener-Tee-Geschenkset-Pi-Lo-Chun-Cover_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/e8/1a/48/Gruener-Tee-Geschenkset-Pi-Lo-Chun-Cover_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=31',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=784',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_TIME',
            'tax' => '0',
        ],
        22 => [
            'id' => '785',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'HTML Editor',
            'articleID' => '32',
            'ordernumber' => 'SW_HTML',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '0',
            'netprice' => '0',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:15:37',
            'modus' => 4,
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => 'checkout',
            'useragent' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => '41e182e0c63a977afacb8853b64bd4e6',
            'customProductIsOncePrice' => '0',
            'customProductMode' => '2',
            'swag_custom_product_original_mode' => 4,
            'shippinginfo' => true,
            'esd' => '0',
            'additional_details' => null,
            'amount' => '0',
            'amountnet' => '0',
            'priceNumeric' => '0',
            'image' => [
                'src' => [
                    'original' => 'http://localhost/customp/media/image/fb/cf/eb/Jasmine-Lotus-Cover.jpg',
                    0 => 'http://localhost/customp/media/image/36/33/c3/Jasmine-Lotus-Cover_200x200.jpg',
                    1 => 'http://localhost/customp/media/image/92/f6/8d/Jasmine-Lotus-Cover_600x600.jpg',
                    2 => 'http://localhost/customp/media/image/8a/2e/07/Jasmine-Lotus-Cover_1280x1280.jpg',
                ],
                'res' => [
                    'original' => [
                        'width' => 0,
                        'height' => 0,
                    ],
                    'description' => '',
                ],
                'position' => 5,
                'extension' => 'jpg',
                'main' => 1,
                'id' => 104,
                'parentId' => null,
                'attribute' => [],
                'srchd' => [
                    0 => 'http://localhost/customp/media/image/d3/e2/cb/Jasmine-Lotus-Cover_200x200@2x.jpg',
                    1 => 'http://localhost/customp/media/image/a5/e9/53/Jasmine-Lotus-Cover_600x600@2x.jpg',
                    2 => 'http://localhost/customp/media/image/5c/63/23/Jasmine-Lotus-Cover_1280x1280@2x.jpg',
                ],
            ],
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=32',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=785',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SW_HTML',
            'tax' => '0',
        ],
        23 => [
            'id' => '790',
            'sessionID' => '91930f4c58a672baa522ef1408ecc1761c1d51dd5fc5f228e61f05dedf072a5d',
            'userID' => '0',
            'articlename' => 'Warenkorbrabatt',
            'articleID' => '0',
            'ordernumber' => 'SHIPPINGDISCOUNT',
            'shippingfree' => '0',
            'quantity' => '1',
            'price' => '-2,00',
            'netprice' => '-1.68',
            'tax_rate' => '19',
            'datum' => '2017-01-16 15:20:04',
            'modus' => '4',
            'esdarticle' => '0',
            'partnerID' => '',
            'lastviewport' => '',
            'useragent' => '',
            'config' => '',
            'currencyFactor' => '1',
            'packunit' => null,
            'mainDetailId' => null,
            'articleDetailId' => null,
            'minpurchase' => 1,
            'taxID' => null,
            'instock' => null,
            'suppliernumber' => null,
            'maxpurchase' => '100',
            'purchasesteps' => 1,
            'purchaseunit' => null,
            'shippingtime' => null,
            'releasedate' => null,
            'sReleaseDate' => null,
            'ean' => null,
            'stockmin' => null,
            'ob_attr1' => null,
            'ob_attr2' => null,
            'ob_attr3' => null,
            'ob_attr4' => null,
            'ob_attr5' => null,
            'ob_attr6' => null,
            'customProductHash' => null,
            'customProductIsOncePrice' => null,
            'customProductMode' => null,
            'shippinginfo' => false,
            'esd' => '0',
            'amount' => '-2,00',
            'amountnet' => '-1,68',
            'priceNumeric' => '-2',
            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=0',
            'linkDelete' => 'shopware.php?sViewport=basket&sDelete=790',
            'linkNote' => 'shopware.php?sViewport=note&sAdd=SHIPPINGDISCOUNT',
            'tax' => '-0,32',
        ],
    ],
    'Amount' => '17,95',
    'AmountNet' => '15,08',
    'Quantity' => 23,
    'AmountNumeric' => 17.949999999999999,
    'AmountNetNumeric' => 15.080000000000002,
    'AmountWithTax' => '0',
    'AmountWithTaxNumeric' => 0.0,
    'sLastActiveArticle' => [
        'id' => '178',
        'link' => 'shopware.php?sViewport=detail&sDetails=178',
    ],
];
