<?php
/**
 * Shopware Premium Plugins
 * Copyright (c) shopware AG
 *
 * According to our dual licensing model, this plugin can be used under
 * a proprietary license as set forth in our Terms and Conditions,
 * section 2.1.2.2 (Conditions of Usage).
 *
 * The text of our proprietary license additionally can be found at and
 * in the LICENSE file you have received along with this plugin.
 *
 * This plugin is distributed in the hope that it will be useful,
 * with LIMITED WARRANTY AND LIABILITY as set forth in our
 * Terms and Conditions, sections 9 (Warranty) and 10 (Liability).
 *
 * "Shopware" is a registered trademark of shopware AG.
 * The licensing of the plugin does not imply a trademark license.
 * Therefore any rights, title and interest in our trademarks
 * remain entirely with us.
 */

return [
    'content' => [
            0 => [
                    'id' => '723',
                    'sessionID' => 'd669008ehnst6gk9utmqpkkojj',
                    'userID' => '0',
                    'articlename' => 'Strandtuch "Ibiza" ',
                    'articleID' => '178',
                    'ordernumber' => 'SW10178',
                    'shippingfree' => '0',
                    'quantity' => '1',
                    'price' => '16,77',
                    'netprice' => '16.77',
                    'tax_rate' => '19',
                    'datum' => '2017-06-16 07:34:11',
                    'modus' => '0',
                    'esdarticle' => '0',
                    'partnerID' => '',
                    'lastviewport' => 'checkout',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => '1',
                    'packunit' => 'Stück',
                    'mainDetailId' => '407',
                    'articleDetailId' => '407',
                    'minpurchase' => '1',
                    'taxID' => '1',
                    'instock' => '84',
                    'suppliernumber' => '',
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => null,
                    'shippingtime' => '',
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => '',
                    'stockmin' => '0',
                    'isFreeGoodByPromotionId' => null,
                    'ob_attr1' => null,
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    'customProductHash' => 'bb06fe423df634e3106415c3766204b8',
                    'customProductIsOncePrice' => '0',
                    'customProductMode' => '1',
                    'shippinginfo' => true,
                    'esd' => '0',
                    'additional_details' => [
                            'articleID' => 178,
                            'articleDetailsID' => 407,
                            'ordernumber' => 'SW10178',
                            'highlight' => false,
                            'description' => 'paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.',
                            'description_long' => '
o decertatio. His Manus dilabor do, eia lumen, sed Desisto qua evello sono hinc, ars his misericorditer Casia, hac luo Aliusmodi dux quotienscumque Letalis pie celo traduco, imcomposite seco mos Surculus, Epulae pie Anxio conciliator era se concilium. Terra quam dicto erro prolecto, quo per incommoditas paulatim Praecepio lex Edoceo sis conticinium Furtum Heidelberg casula Toto pes an jugiter pe.

',
                            'esd' => false,
                            'articleName' => 'Strandtuch "Ibiza"',
                            'taxID' => 1,
                            'tax' => 19.0,
                            'instock' => 84,
                            'isAvailable' => true,
                            'weight' => 0.0,
                            'shippingtime' => null,
                            'pricegroupActive' => false,
                            'pricegroupID' => null,
                            'length' => 0.0,
                            'height' => 0.0,
                            'width' => 0.0,
                            'laststock' => false,
                            'additionaltext' => '',
                            'datum' => '2012-08-21',
                            'sales' => 0,
                            'filtergroupID' => null,
                            'priceStartingFrom' => null,
                            'pseudopricePercent' => null,
                            'sVariantArticle' => null,
                            'sConfigurator' => false,
                            'metaTitle' => null,
                            'shippingfree' => false,
                            'suppliernumber' => '',
                            'notification' => false,
                            'ean' => '',
                            'keywords' => '',
                            'sReleasedate' => '',
                            'template' => '',
                            'attributes' => [
                                    'core' => [
                                            'storage' => [
                                                    'id' => '429',
                                                    'articleID' => '178',
                                                    'articledetailsID' => '407',
                                                    'attr1' => '',
                                                    'attr2' => '',
                                                    'attr3' => '',
                                                    'attr4' => '',
                                                    'attr5' => '',
                                                    'attr6' => '',
                                                    'attr7' => '',
                                                    'attr8' => '',
                                                    'attr9' => '',
                                                    'attr10' => '',
                                                    'attr11' => '',
                                                    'attr12' => '',
                                                    'attr13' => '',
                                                    'attr14' => '',
                                                    'attr15' => '',
                                                    'attr16' => '',
                                                    'attr17' => null,
                                                    'attr18' => '',
                                                    'attr19' => '',
                                                    'attr20' => '',
                                                ],
                                        ],
                                    'marketing' => [
                                            'isNew' => false,
                                            'isTopSeller' => false,
                                            'comingSoon' => false,
                                            'storage' => [
                                                ],
                                        ],
                                ],
                            'allowBuyInListing' => false,
                            'attr1' => '',
                            'attr2' => '',
                            'attr3' => '',
                            'attr4' => '',
                            'attr5' => '',
                            'attr6' => '',
                            'attr7' => '',
                            'attr8' => '',
                            'attr9' => '',
                            'attr10' => '',
                            'attr11' => '',
                            'attr12' => '',
                            'attr13' => '',
                            'attr14' => '',
                            'attr15' => '',
                            'attr16' => '',
                            'attr17' => null,
                            'attr18' => '',
                            'attr19' => '',
                            'attr20' => '',
                            'supplierName' => 'Beachdreams Clothes',
                            'supplierImg' => 'http://shopware53.localhost/media/image/a1/f7/82/beachdreams.png',
                            'supplierID' => 12,
                            'supplierDescription' => '',
                            'supplier_attributes' => [
                                ],
                            'newArticle' => false,
                            'sUpcoming' => false,
                            'topseller' => false,
                            'valFrom' => 1,
                            'valTo' => null,
                            'from' => 1,
                            'to' => null,
                            'price' => '16,77',
                            'pseudoprice' => '0',
                            'referenceprice' => '0',
                            'has_pseudoprice' => false,
                            'price_numeric' => 16.765,
                            'pseudoprice_numeric' => 0.0,
                            'price_attributes' => [
                                ],
                            'pricegroup' => 'EK',
                            'minpurchase' => 1,
                            'maxpurchase' => '100',
                            'purchasesteps' => 1,
                            'purchaseunit' => null,
                            'referenceunit' => null,
                            'packunit' => 'Stück',
                            'unitID' => null,
                            'sUnit' => [
                                    'unit' => null,
                                    'description' => null,
                                ],
                            'unit_attributes' => [
                                ],
                            'image' => [
                                    'id' => 445,
                                    'position' => null,
                                    'source' => 'http://shopware53.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                                    'description' => '',
                                    'extension' => 'jpg',
                                    'main' => true,
                                    'parentId' => null,
                                    'width' => 1698,
                                    'height' => 1131,
                                    'thumbnails' => [
                                            0 => [
                                                    'source' => 'http://shopware53.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                                                    'retinaSource' => 'http://shopware53.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                                                    'sourceSet' => 'http://shopware53.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://shopware53.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                                                    'maxWidth' => '200',
                                                    'maxHeight' => '200',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            1 => [
                                                    'source' => 'http://shopware53.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                                                    'retinaSource' => 'http://shopware53.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                                                    'sourceSet' => 'http://shopware53.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://shopware53.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                                                    'maxWidth' => '600',
                                                    'maxHeight' => '600',
                                                    'attributes' => [
                                                        ],
                                                ],
                                            2 => [
                                                    'source' => 'http://shopware53.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                                                    'retinaSource' => 'http://shopware53.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                                                    'sourceSet' => 'http://shopware53.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://shopware53.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                                                    'maxWidth' => '1280',
                                                    'maxHeight' => '1280',
                                                    'attributes' => [
                                                        ],
                                                ],
                                        ],
                                    'attributes' => [
                                        ],
                                    'attribute' => [
                                        ],
                                ],
                            'prices' => [
                                    0 => [
                                            'valFrom' => 1,
                                            'valTo' => null,
                                            'from' => 1,
                                            'to' => null,
                                            'price' => '16,77',
                                            'pseudoprice' => '0',
                                            'referenceprice' => '0',
                                            'pseudopricePercent' => null,
                                            'has_pseudoprice' => false,
                                            'price_numeric' => 16.765,
                                            'pseudoprice_numeric' => 0.0,
                                            'price_attributes' => [
                                                ],
                                            'pricegroup' => 'EK',
                                            'minpurchase' => 1,
                                            'maxpurchase' => '100',
                                            'purchasesteps' => 1,
                                            'purchaseunit' => null,
                                            'referenceunit' => null,
                                            'packunit' => 'Stück',
                                            'unitID' => null,
                                            'sUnit' => [
                                                    'unit' => null,
                                                    'description' => null,
                                                ],
                                            'unit_attributes' => [
                                                ],
                                        ],
                                ],
                            'linkBasket' => 'shopware.php?sViewport=basket&sAdd=SW10178',
                            'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178&number=SW10178',
                        ],
                    'amountWithTax' => 19.9563,
                    'amount' => '16,77',
                    'amountnet' => '16,77',
                    'priceNumeric' => '16.765',
                    'image' => [
                            'id' => 445,
                            'position' => null,
                            'source' => 'http://shopware53.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                            'description' => '',
                            'extension' => 'jpg',
                            'main' => true,
                            'parentId' => null,
                            'width' => 1698,
                            'height' => 1131,
                            'thumbnails' => [
                                    0 => [
                                            'source' => 'http://shopware53.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                                            'retinaSource' => 'http://shopware53.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                                            'sourceSet' => 'http://shopware53.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg, http://shopware53.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg 2x',
                                            'maxWidth' => '200',
                                            'maxHeight' => '200',
                                            'attributes' => [
                                                ],
                                        ],
                                    1 => [
                                            'source' => 'http://shopware53.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                                            'retinaSource' => 'http://shopware53.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                                            'sourceSet' => 'http://shopware53.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg, http://shopware53.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg 2x',
                                            'maxWidth' => '600',
                                            'maxHeight' => '600',
                                            'attributes' => [
                                                ],
                                        ],
                                    2 => [
                                            'source' => 'http://shopware53.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                                            'retinaSource' => 'http://shopware53.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                                            'sourceSet' => 'http://shopware53.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg, http://shopware53.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg 2x',
                                            'maxWidth' => '1280',
                                            'maxHeight' => '1280',
                                            'attributes' => [
                                                ],
                                        ],
                                ],
                            'attributes' => [
                                ],
                            'attribute' => [
                                ],
                            'src' => [
                                    'original' => 'http://shopware53.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                                    0 => 'http://shopware53.localhost/media/image/1b/23/da/Strandtuch-mit-Flip-Flops-gelb_200x200.jpg',
                                    1 => 'http://shopware53.localhost/media/image/47/1d/25/Strandtuch-mit-Flip-Flops-gelb_600x600.jpg',
                                    2 => 'http://shopware53.localhost/media/image/08/d2/70/Strandtuch-mit-Flip-Flops-gelb_1280x1280.jpg',
                                ],
                            'srchd' => [
                                    'original' => 'http://shopware53.localhost/media/image/3c/80/e0/Strandtuch-mit-Flip-Flops-gelb.jpg',
                                    0 => 'http://shopware53.localhost/media/image/45/e6/5f/Strandtuch-mit-Flip-Flops-gelb_200x200@2x.jpg',
                                    1 => 'http://shopware53.localhost/media/image/1f/a8/51/Strandtuch-mit-Flip-Flops-gelb_600x600@2x.jpg',
                                    2 => 'http://shopware53.localhost/media/image/87/9c/e9/Strandtuch-mit-Flip-Flops-gelb_1280x1280@2x.jpg',
                                ],
                            'res' => [
                                    'original' => [
                                            'width' => 1131,
                                            'height' => 1698,
                                        ],
                                ],
                        ],
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=178',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=723',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=SW10178',
                    'tax' => '3,19',
                    'custom_product_adds' => [
                            2 => [
                                    'id' => '2',
                                    'template_id' => '1',
                                    'name' => 'text1',
                                    'description' => '',
                                    'ordernumber' => '',
                                    'required' => '0',
                                    'type' => 'textfield',
                                    'position' => '0',
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'is_once_surcharge' => '0',
                                    'max_text_length' => null,
                                    'min_value' => null,
                                    'max_value' => null,
                                    'max_file_size' => '3145728',
                                    'min_date' => null,
                                    'max_date' => null,
                                    'max_files' => '1',
                                    'interval' => null,
                                    'could_contain_values' => '0',
                                    'allows_multiple_selection' => '0',
                                    'prices' => [
                                            0 => [
                                                    'id' => '2',
                                                    'option_id' => '2',
                                                    'value_id' => null,
                                                    'surcharge' => '8.4033613445378',
                                                    'percentage' => '0',
                                                    'is_percentage_surcharge' => '0',
                                                    'tax_id' => '1',
                                                    'customer_group_name' => 'Shopkunden',
                                                    'customer_group_id' => '1',
                                                ],
                                        ],
                                    'netPrice' => 8.4033613445378,
                                    'surcharge' => 8.4033613445378,
                                    'tax_id' => '1',
                                    'tax' => 1.6,
                                    'isTaxFreeDelivery' => false,
                                    'values' => [
                                        ],
                                    'selectedValue' => [
                                            0 => 'TestText1',
                                        ],
                                ],
                            3 => [
                                    'id' => '3',
                                    'template_id' => '1',
                                    'name' => 'checkbox',
                                    'description' => '',
                                    'ordernumber' => '',
                                    'required' => '0',
                                    'type' => 'checkbox',
                                    'position' => '1',
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'is_once_surcharge' => '0',
                                    'max_text_length' => null,
                                    'min_value' => null,
                                    'max_value' => null,
                                    'max_file_size' => '3145728',
                                    'min_date' => null,
                                    'max_date' => null,
                                    'max_files' => '1',
                                    'interval' => null,
                                    'could_contain_values' => '1',
                                    'allows_multiple_selection' => '0',
                                    'prices' => [
                                            0 => [
                                                    'id' => '5',
                                                    'option_id' => '3',
                                                    'value_id' => null,
                                                    'surcharge' => '8.4033613445378',
                                                    'percentage' => '0',
                                                    'is_percentage_surcharge' => '0',
                                                    'tax_id' => '1',
                                                    'customer_group_name' => 'Shopkunden',
                                                    'customer_group_id' => '1',
                                                ],
                                        ],
                                    'netPrice' => 8.4033613445378,
                                    'surcharge' => 8.4033613445378,
                                    'tax_id' => '1',
                                    'tax' => 1.6,
                                    'isTaxFreeDelivery' => false,
                                    'values' => [
                                            0 => [
                                                    'id' => '1',
                                                    'option_id' => '3',
                                                    'name' => 'value1',
                                                    'ordernumber' => 'value1',
                                                    'value' => '',
                                                    'is_default_value' => '0',
                                                    'position' => '0',
                                                    'is_once_surcharge' => '0',
                                                    'media_id' => null,
                                                    'seo_title' => null,
                                                    'prices' => [
                                                            0 => [
                                                                    'id' => '3',
                                                                    'option_id' => null,
                                                                    'value_id' => '1',
                                                                    'surcharge' => '16.806722689076',
                                                                    'percentage' => '0',
                                                                    'is_percentage_surcharge' => '0',
                                                                    'tax_id' => '1',
                                                                    'customer_group_name' => 'Shopkunden',
                                                                    'customer_group_id' => '1',
                                                                ],
                                                        ],
                                                    'netPrice' => 16.806722689076,
                                                    'surcharge' => 16.806722689076,
                                                    'tax_id' => '1',
                                                    'tax' => 3.19,
                                                    'isTaxFreeDelivery' => false,
                                                ],
                                            1 => [
                                                    'id' => '2',
                                                    'option_id' => '3',
                                                    'name' => 'value2',
                                                    'ordernumber' => 'value2',
                                                    'value' => '',
                                                    'is_default_value' => '0',
                                                    'position' => '1',
                                                    'is_once_surcharge' => '0',
                                                    'media_id' => null,
                                                    'seo_title' => null,
                                                    'prices' => [
                                                            0 => [
                                                                    'id' => '4',
                                                                    'option_id' => null,
                                                                    'value_id' => '2',
                                                                    'surcharge' => '16.806722689076',
                                                                    'percentage' => '0',
                                                                    'is_percentage_surcharge' => '0',
                                                                    'tax_id' => '1',
                                                                    'customer_group_name' => 'Shopkunden',
                                                                    'customer_group_id' => '1',
                                                                ],
                                                        ],
                                                    'netPrice' => 16.806722689076,
                                                    'surcharge' => 16.806722689076,
                                                    'tax_id' => '1',
                                                    'tax' => 3.19,
                                                    'isTaxFreeDelivery' => false,
                                                ],
                                        ],
                                    'selectedValue' => [
                                            0 => '1',
                                            1 => '2',
                                        ],
                                ],
                        ],
                    'custom_product_prices' => [
                            'quantity' => '1',
                            'basePrice' => 16.76,
                            'onlySurcharges' => 50.42,
                            'customProduct' => 67.18,
                            'total' => 67.18,
                            'surchargesTotal' => 50.42,
                        ],
                ],
            1 => [
                    'id' => '724',
                    'sessionID' => 'd669008ehnst6gk9utmqpkkojj',
                    'userID' => '0',
                    'articlename' => 'text1',
                    'articleID' => '2',
                    'ordernumber' => '',
                    'shippingfree' => '0',
                    'quantity' => '1',
                    'price' => '8,40',
                    'netprice' => '8.4033613445378',
                    'tax_rate' => '19',
                    'datum' => '2017-06-16 07:34:11',
                    'modus' => 0,
                    'esdarticle' => '0',
                    'partnerID' => '',
                    'lastviewport' => 'checkout',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => '1',
                    'packunit' => null,
                    'mainDetailId' => null,
                    'articleDetailId' => null,
                    'minpurchase' => 1,
                    'taxID' => null,
                    'instock' => null,
                    'suppliernumber' => null,
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => null,
                    'shippingtime' => null,
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => null,
                    'stockmin' => null,
                    'isFreeGoodByPromotionId' => null,
                    'ob_attr1' => null,
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    'customProductHash' => 'bb06fe423df634e3106415c3766204b8',
                    'customProductIsOncePrice' => '0',
                    'customProductMode' => '2',
                    'swag_custom_product_original_mode' => 4,
                    'shippinginfo' => true,
                    'esd' => '0',
                    'additional_details' => null,
                    'amountWithTax' => 9.996,
                    'amount' => '8,40',
                    'amountnet' => '8,40',
                    'priceNumeric' => '8.4033613445378',
                    'image' => [
                            'src' => [
                                    'original' => 'http://shopware53.localhost/media/image/8b/7f/29/Muensterlaender_Lagerkorn.jpg',
                                    0 => 'http://shopware53.localhost/media/image/95/c0/a3/Muensterlaender_Lagerkorn_200x200.jpg',
                                    1 => 'http://shopware53.localhost/media/image/cd/04/6a/Muensterlaender_Lagerkorn_600x600.jpg',
                                    2 => 'http://shopware53.localhost/media/image/79/08/c1/Muensterlaender_Lagerkorn_1280x1280.jpg',
                                ],
                            'res' => [
                                    'original' => [
                                            'width' => 0,
                                            'height' => 0,
                                        ],
                                    'description' => '',
                                ],
                            'position' => 2,
                            'extension' => 'jpg',
                            'main' => 1,
                            'id' => 5,
                            'parentId' => null,
                            'attribute' => [
                                ],
                            'srchd' => [
                                    0 => 'http://shopware53.localhost/media/image/c8/b6/3e/Muensterlaender_Lagerkorn_200x200@2x.jpg',
                                    1 => 'http://shopware53.localhost/media/image/06/aa/82/Muensterlaender_Lagerkorn_600x600@2x.jpg',
                                    2 => 'http://shopware53.localhost/media/image/2b/a1/36/Muensterlaender_Lagerkorn_1280x1280@2x.jpg',
                                ],
                        ],
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=2',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=724',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=',
                    'tax' => '1,60',
                    'customProductOption' => [
                            'id' => '2',
                            'template_id' => '1',
                            'name' => 'text1',
                            'description' => '',
                            'ordernumber' => '',
                            'required' => '0',
                            'type' => 'textfield',
                            'position' => '0',
                            'default_value' => '',
                            'placeholder' => '',
                            'is_once_surcharge' => '0',
                            'max_text_length' => null,
                            'min_value' => null,
                            'max_value' => null,
                            'max_file_size' => '3145728',
                            'min_date' => null,
                            'max_date' => null,
                            'max_files' => '1',
                            'interval' => null,
                            'could_contain_values' => '0',
                            'allows_multiple_selection' => '0',
                            'prices' => [
                                    0 => [
                                            'id' => '2',
                                            'option_id' => '2',
                                            'value_id' => null,
                                            'surcharge' => '8.4033613445378',
                                            'percentage' => '0',
                                            'is_percentage_surcharge' => '0',
                                            'tax_id' => '1',
                                            'customer_group_name' => 'Shopkunden',
                                            'customer_group_id' => '1',
                                        ],
                                ],
                            'netPrice' => 8.4033613445378,
                            'surcharge' => 8.4033613445378,
                            'tax_id' => '1',
                            'tax' => 1.6,
                            'isTaxFreeDelivery' => false,
                            'values' => [
                                ],
                            'selectedValue' => [
                                    0 => 'TestText1',
                                ],
                        ],
                ],
            2 => [
                    'id' => '725',
                    'sessionID' => 'd669008ehnst6gk9utmqpkkojj',
                    'userID' => '0',
                    'articlename' => 'checkbox',
                    'articleID' => '3',
                    'ordernumber' => '',
                    'shippingfree' => '0',
                    'quantity' => '1',
                    'price' => '8,40',
                    'netprice' => '8.4033613445378',
                    'tax_rate' => '19',
                    'datum' => '2017-06-16 07:34:11',
                    'modus' => 0,
                    'esdarticle' => '0',
                    'partnerID' => '',
                    'lastviewport' => 'checkout',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => '1',
                    'packunit' => null,
                    'mainDetailId' => null,
                    'articleDetailId' => null,
                    'minpurchase' => 1,
                    'taxID' => null,
                    'instock' => null,
                    'suppliernumber' => null,
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => null,
                    'shippingtime' => null,
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => null,
                    'stockmin' => null,
                    'isFreeGoodByPromotionId' => null,
                    'ob_attr1' => null,
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    'customProductHash' => 'bb06fe423df634e3106415c3766204b8',
                    'customProductIsOncePrice' => '0',
                    'customProductMode' => '2',
                    'swag_custom_product_original_mode' => 4,
                    'shippinginfo' => true,
                    'esd' => '0',
                    'additional_details' => null,
                    'amountWithTax' => 9.996,
                    'amount' => '8,40',
                    'amountnet' => '8,40',
                    'priceNumeric' => '8.4033613445378',
                    'image' => [
                            'src' => [
                                    'original' => 'http://shopware53.localhost/media/image/8a/ed/c0/Muensterlaender_Aperitif_Flasche.jpg',
                                    0 => 'http://shopware53.localhost/media/image/06/61/39/Muensterlaender_Aperitif_Flasche_200x200.jpg',
                                    1 => 'http://shopware53.localhost/media/image/94/be/15/Muensterlaender_Aperitif_Flasche_600x600.jpg',
                                    2 => 'http://shopware53.localhost/media/image/cd/0b/a1/Muensterlaender_Aperitif_Flasche_1280x1280.jpg',
                                ],
                            'res' => [
                                    'original' => [
                                            'width' => 0,
                                            'height' => 0,
                                        ],
                                    'description' => '',
                                ],
                            'position' => 1,
                            'extension' => 'jpg',
                            'main' => 1,
                            'id' => 6,
                            'parentId' => null,
                            'attribute' => [
                                ],
                            'srchd' => [
                                    0 => 'http://shopware53.localhost/media/image/3b/1e/23/Muensterlaender_Aperitif_Flasche_200x200@2x.jpg',
                                    1 => 'http://shopware53.localhost/media/image/72/5f/81/Muensterlaender_Aperitif_Flasche_600x600@2x.jpg',
                                    2 => 'http://shopware53.localhost/media/image/bd/e5/b6/Muensterlaender_Aperitif_Flasche_1280x1280@2x.jpg',
                                ],
                        ],
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=3',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=725',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=',
                    'tax' => '1,60',
                ],
            3 => [
                    'id' => '726',
                    'sessionID' => 'd669008ehnst6gk9utmqpkkojj',
                    'userID' => '0',
                    'articlename' => 'value1',
                    'articleID' => '1',
                    'ordernumber' => 'value1',
                    'shippingfree' => '0',
                    'quantity' => '1',
                    'price' => '16,81',
                    'netprice' => '16.806722689076',
                    'tax_rate' => '19',
                    'datum' => '2017-06-16 07:34:11',
                    'modus' => 0,
                    'esdarticle' => '0',
                    'partnerID' => '',
                    'lastviewport' => 'checkout',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => '1',
                    'packunit' => null,
                    'mainDetailId' => null,
                    'articleDetailId' => null,
                    'minpurchase' => 1,
                    'taxID' => null,
                    'instock' => null,
                    'suppliernumber' => null,
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => null,
                    'shippingtime' => null,
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => null,
                    'stockmin' => null,
                    'isFreeGoodByPromotionId' => null,
                    'ob_attr1' => null,
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    'customProductHash' => 'bb06fe423df634e3106415c3766204b8',
                    'customProductIsOncePrice' => '0',
                    'customProductMode' => '3',
                    'swag_custom_product_original_mode' => 4,
                    'shippinginfo' => true,
                    'esd' => '0',
                    'additional_details' => null,
                    'amountWithTax' => 20.0039,
                    'amount' => '16,81',
                    'amountnet' => '16,81',
                    'priceNumeric' => '16.806722689076',
                    'image' => [
                        ],
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=1',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=726',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=value1',
                    'tax' => '3,19',
                ],
            4 => [
                    'id' => '727',
                    'sessionID' => 'd669008ehnst6gk9utmqpkkojj',
                    'userID' => '0',
                    'articlename' => 'value2',
                    'articleID' => '2',
                    'ordernumber' => 'value2',
                    'shippingfree' => '0',
                    'quantity' => '1',
                    'price' => '16,81',
                    'netprice' => '16.806722689076',
                    'tax_rate' => '19',
                    'datum' => '2017-06-16 07:34:11',
                    'modus' => 0,
                    'esdarticle' => '0',
                    'partnerID' => '',
                    'lastviewport' => 'checkout',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => '1',
                    'packunit' => null,
                    'mainDetailId' => null,
                    'articleDetailId' => null,
                    'minpurchase' => 1,
                    'taxID' => null,
                    'instock' => null,
                    'suppliernumber' => null,
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => null,
                    'shippingtime' => null,
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => null,
                    'stockmin' => null,
                    'isFreeGoodByPromotionId' => null,
                    'ob_attr1' => null,
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    'customProductHash' => 'bb06fe423df634e3106415c3766204b8',
                    'customProductIsOncePrice' => '0',
                    'customProductMode' => '3',
                    'swag_custom_product_original_mode' => 4,
                    'shippinginfo' => true,
                    'esd' => '0',
                    'additional_details' => null,
                    'amountWithTax' => 20.0039,
                    'amount' => '16,81',
                    'amountnet' => '16,81',
                    'priceNumeric' => '16.806722689076',
                    'image' => [
                            'src' => [
                                    'original' => 'http://shopware53.localhost/media/image/8b/7f/29/Muensterlaender_Lagerkorn.jpg',
                                    0 => 'http://shopware53.localhost/media/image/95/c0/a3/Muensterlaender_Lagerkorn_200x200.jpg',
                                    1 => 'http://shopware53.localhost/media/image/cd/04/6a/Muensterlaender_Lagerkorn_600x600.jpg',
                                    2 => 'http://shopware53.localhost/media/image/79/08/c1/Muensterlaender_Lagerkorn_1280x1280.jpg',
                                ],
                            'res' => [
                                    'original' => [
                                            'width' => 0,
                                            'height' => 0,
                                        ],
                                    'description' => '',
                                ],
                            'position' => 2,
                            'extension' => 'jpg',
                            'main' => 1,
                            'id' => 5,
                            'parentId' => null,
                            'attribute' => [
                                ],
                            'srchd' => [
                                    0 => 'http://shopware53.localhost/media/image/c8/b6/3e/Muensterlaender_Lagerkorn_200x200@2x.jpg',
                                    1 => 'http://shopware53.localhost/media/image/06/aa/82/Muensterlaender_Lagerkorn_600x600@2x.jpg',
                                    2 => 'http://shopware53.localhost/media/image/2b/a1/36/Muensterlaender_Lagerkorn_1280x1280@2x.jpg',
                                ],
                        ],
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=2',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=727',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=value2',
                    'tax' => '3,19',
                ],
            5 => [
                    'id' => '729',
                    'sessionID' => 'd669008ehnst6gk9utmqpkkojj',
                    'userID' => '0',
                    'articlename' => 'Warenkorbrabatt',
                    'articleID' => '0',
                    'ordernumber' => 'SHIPPINGDISCOUNT',
                    'shippingfree' => '0',
                    'quantity' => '1',
                    'price' => '-2,00',
                    'netprice' => '-2',
                    'tax_rate' => '19',
                    'datum' => '2017-06-16 07:34:20',
                    'modus' => '4',
                    'esdarticle' => '0',
                    'partnerID' => '',
                    'lastviewport' => 'checkout',
                    'useragent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
                    'config' => '',
                    'currencyFactor' => '1',
                    'packunit' => null,
                    'mainDetailId' => null,
                    'articleDetailId' => null,
                    'minpurchase' => 1,
                    'taxID' => null,
                    'instock' => null,
                    'suppliernumber' => null,
                    'maxpurchase' => '100',
                    'purchasesteps' => 1,
                    'purchaseunit' => null,
                    'shippingtime' => null,
                    'releasedate' => null,
                    'sReleaseDate' => null,
                    'ean' => null,
                    'stockmin' => null,
                    'isFreeGoodByPromotionId' => null,
                    'ob_attr1' => null,
                    'ob_attr2' => null,
                    'ob_attr3' => null,
                    'ob_attr4' => null,
                    'ob_attr5' => null,
                    'ob_attr6' => null,
                    'customProductHash' => null,
                    'customProductIsOncePrice' => null,
                    'customProductMode' => null,
                    'shippinginfo' => false,
                    'esd' => '0',
                    'amountWithTax' => -2.38,
                    'amount' => '-2,00',
                    'amountnet' => '-2,00',
                    'priceNumeric' => '-2',
                    'linkDetails' => 'shopware.php?sViewport=detail&sArticle=0',
                    'linkDelete' => 'shopware.php?sViewport=basket&sDelete=729',
                    'linkNote' => 'shopware.php?sViewport=note&sAdd=SHIPPINGDISCOUNT',
                    'tax' => '-0,38',
                ],
        ],
    'Amount' => '65,19',
    'AmountNet' => '65,19',
    'Quantity' => 5,
    'AmountNumeric' => 65.19,
    'AmountNetNumeric' => 65.19,
    'AmountWithTax' => '77,58',
    'AmountWithTaxNumeric' => 77.58000000000001,
];
